apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-bash-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine-bash
  template:
    metadata:
      labels:
        app: alpine-bash
    spec:
      containers:
      - name: alpine-bash
        image: alpine:latest
        command: ["sleep", "infinity"]
        ports:
        - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: alpine-bash-service
spec:
  selector:
    app: alpine-bash
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: ClusterIP


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alpine-bash-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: your-domain.com  # Replace with your actual domain or IP
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: alpine-bash-service
            port:
              number: 8888
